### ISSUE TITLE
Telegraf role

### ISSUE THREAD

**Issue by NickHauptvogel** [raynix/ansible-kubeadm#1]
Hi,

what do I need the telegraf role in the playbook for? Is it required for kubeadm to work?

Regards

Nick

**Comment by raynix** [comment]
Hi this is optional, just to monitor the PIs. I plan to replace telegraf
with Prometheus.

**Comment by raynix** [comment]
Made it optional here. https://github.com/raynix/ansible-kubeadm/commit/6a3b8dfc192e926e196606ed7ff555fb457e7ac7
